### PR TITLE
Update Bundles

### PR DESCRIPTION
**Pull request by shayancanonical**
Update bundles with new revisions from Charmhub.

### CODE REVIEW

**Review by taurus-forever — APPROVED** [review]

**Comment by taurus-forever** [comment]
> to rev 87?

1) update_bundle.py needs to be improved. It uses the first element in the channel-map,
while for the mysql repo we have two records there:
 revision=86 for "20.04"
 revision=87 for "22.04"

```
curl https://api.snapcraft.io/v2/charms/info/mysql?fields=channel-map | jq
{
  "channel-map": [
    {
      "channel": {
        "base": {
          "channel": "20.04",
...
        "revision": 86,
        "version": "86"
      }
    },
    {
      "channel": {
        "base": {
          "channel": "22.04",
...
        "revision": 87,
        "version": "87"
...
```

2) Why revision 87 is missing for 22.04 is another [good question](https://github.com/canonical/mysql-operator/actions?query=branch%3Amain).

Anyway, this can be submitted AS IS.

**Comment by shayancanonical** [comment]
@taurus-forever
for (2), revision 87 was manually uploaded to charmhub specifically for 22.04 (which is why it is missing for 20.04). Furthermore, the custom canonical github action to upload to charmhub picks only one `.charm` file to upload when there are multiple `.charm` files produced. This is why we had to manually upload a file for 22.04

**Comment by taurus-forever** [comment]
> This is why we had to manually upload a file for 22.04

Can we tweak Makefile in a way to upload both .charm files automatically?

**Comment by shayancanonical** [comment]
@taurus-forever 
> Can we tweak Makefile in a way to upload both .charm files automatically?
The mysql-bundle repo has a makefile since there is no charming action to upload bundles. However, the mysql operator uses the upload-charm action (which currently only uploads one charm package). Should we continue using the github action (and possibly update the JS code to allow upload of multiple charm files), or should we adopt a Makefile in the mysql operator and use charmcraft directly?

**Comment by taurus-forever** [comment]
> The mysql-bundle repo has a makefile since there is no github action to upload bundles. ...

Isn't it upload-bundle: https://github.com/canonical/charming-actions/tree/main/upload-bundle ?

**Comment by taurus-forever** [comment]
@shayancanonical I have merged to use the latest version in my tests, I hope it is OK.

**Pull request merged**
